version: '3'
services:
  postgresql:
    image: postgres
    container_name: my-hms
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydb

  redis:
    image: redis
    container_name: redis-hms
    ports:
      - "6379:6379"
